# Generated by Django 4.0.5 on 2022-06-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('title1', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=1000)),
                ('text1', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Body1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilis', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='End',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('card', models.CharField(max_length=100)),
                ('card2', models.TextField(max_length=1000)),
                ('btn', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link1', models.CharField(max_length=50)),
                ('link2', models.CharField(max_length=100)),
                ('link3', models.CharField(max_length=100)),
                ('link4', models.CharField(max_length=100)),
                ('h1', models.CharField(max_length=200)),
                ('h2', models.CharField(max_length=200)),
                ('btn1', models.CharField(max_length=100)),
                ('btn2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Slayd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
